name: Codecov check

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/codecov.yml"
      - ".github/scripts/coverage.sh"
      - "src/**"
      - "scripts/**"
      - "test/**"

defaults:
  run:
    shell: bash

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install lcov
        run: sudo apt install lcov -y

      - name: Build
        run: ./scripts/compile.sh -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=ON

      - name: Run tests and collect lcov report
        run: .github/scripts/coverage.sh

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.info
          fail_ci_if_error: true
          verbose: true
