name: Codecov check

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true

defaults:
  run:
    shell: bash

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Compile and run tests
        uses: addnab/docker-run-action@v3
        with:
          image: jihoonjang2/automata:hw1
          shell: bash
          options: -v ${{ github.workspace }}:/work
          run: |
            apt install lcov -y
            cd /work
            scripts/compile.sh -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=ON
            .github/scripts/coverage.sh

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.info
          fail_ci_if_error: true
          verbose: true
