name: Create release

on:
  push:
    tags:
      - "*"

defaults:
  run:
    shell: bash

jobs:
  run-codecov:
    uses: ./.github/workflows/codecov.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  release:
    needs: run-codecov

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build report
        uses: xu-cheng/latex-action@v2
        with:
          root_file: doc/*.tex
          glob_root_file: true
          latexmk_use_xelatex: true
          args: "-xelatex -synctex=1 -interaction=nonstopmode -file-line-error"

      - name: Create zip archive
        run: .github/scripts/release.sh

      - name: Upload to github
        uses: softprops/action-gh-release@v1
        with:
          files: "*.zip"
          fail_on_unmatched_files: true
          generate_release_notes: true
